language: node_js
node_js:
  - "14"
dist: trusty
sudo: required
branches:
  only:
  - master
before_install:
- sudo apt-get install sshpass
before_script:
  - chmod -R a+x scripts
  - npm install -g npm@14.15.4 
  - npm install -g @angular/cli
script:
- ./scripts/travis-build.sh
- ./scripts/travis-success.sh
after_success:
  - echo Deploy to server $IP on branch $TRAVIS_BRANCH
  - ./scripts/travis-deploy.sh